spring.jpa.defer-datasource-initialization=true
# Ensure schema is created before data.sql
#spring.jpa.hibernate.ddl-auto=create
# H2 Credentials
spring.application.name=Backend

# H2 Embedded Database (FIX)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true